# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170502_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(default=datetime.datetime(2017, 5, 6, 11, 8, 30, 395074, tzinfo=utc), max_length=240),
            preserve_default=False,
        ),
    ]
